### PR TITLE
prevent double-slash in asset paths (//assets/ --> /assets/)

### LINKED ISSUE #912: Typo in Example Code - textToContours()
### Most appropriate sections of the p5.js website?

Home

### What is your operating system?

None

### Web browser and version

_No response_

### Actual Behavior

Need to fix // -> / in [textToContours](https://beta.p5js.org/reference/p5.font/texttocontours/)

Image

### Expected Behavior

Need to fix // -> / in [textToContours](https://beta.p5js.org/reference/p5.font/texttocontours/)

Image

### Steps to reproduce

_No response_

### Would you like to work on the issue?

-

### PR DESCRIPTION
**Pull request by perminder-17**
Resolves #912 

I also build the reference again in the website, and commited the regenerated MDX, and included those files in the PR as well.

### CODE REVIEW

File: src/scripts/builders/reference.ts [hunk 1]
```diff
@@ -161,8 +161,8 @@ const correctRelativeLinksToExampleAssets = (
     return content;
   }
   return Array.isArray(content)
-    ? content.map((ex) => ex.replaceAll("assets/", "/assets/").replaceAll(/\n$/g, ""))
-    : content.replaceAll("assets/", "/assets/");
+  ? content.map((ex) => ex.replaceAll(/(?<!\/)assets\//g, "/assets/").replaceAll(/\n$/g, ""))
```
Comment (ksen0) [inline src/scripts/builders/reference.ts:164]: Nice!

**Comment by ksen0** [comment]
Hi @perminder-17 , thanks for this, it looks good. OK to merge!

Not sure if you've come across it, but FYI there's a related, but not quite duplicate (on `main` not `2.0`, and about absolute not relative links), is https://github.com/processing/p5.js-website/issues/878 (see also the [comment on that PR](https://github.com/processing/p5.js-website/pull/892#issuecomment-3133005718))

**Review by ksen0 — APPROVED** [review]

**Comment by perminder-17** [comment]
> Not sure if you've come across it, but FYI there's a related, but not quite duplicate (on main not 2.0, and about absolute not relative links), is https://github.com/processing/p5.js-website/issues/878 (see also the https://github.com/processing/p5.js-website/pull/892#issuecomment-3133005718)

Just added a comment on that, https://github.com/processing/p5.js-website/pull/892#issuecomment-3176768307
Looks like I found the issue contributor was facing. I can probably help her out :)

**Comment by davepagurek** [comment]
hey @ksen0, just noticed this again in the reference, anything else we need to do here before merging?
