### PR TITLE
fixed reference classes don't show up in filter search

### LINKED ISSUE #717: In the references, classes don't show up in the filter search
### Most appropriate sections of the p5.js website?

Reference

### What is your operating system?

Mac OS

### Web browser and version

Firefox 135

### Actual Behavior

If I filter for "Element", `p5.Element` doesn't show up:

Image

### Expected Behavior

It does exist, it's just a subcategory of DOM (at the bottom of this screenshot):

Image

We probably need to include subcategory names in the filtering.

### Steps to reproduce

_No response_

### Would you like to work on the issue?

Someone else is free to implement this!

### PR DESCRIPTION
**Pull request by webermayank**
Fixes #717
 
earlier classes was not showing in filer search, after i modified the code and added a check , classes comes up in filter search 
| Before | After |
|--------|-------|
| image | image|

more example 
| Before | After |
|--------|--------|
| Screenshot 2025-04-11 225919 | Screenshot 2025-04-11 225928|

@ksen0  , @davepagurek - please verify if this is correct. Tell me if something needs to be changed

### CODE REVIEW

File: src/components/ReferenceDirectoryWithFilter/index.tsx [hunk 1]
```diff
@@ -72,18 +72,26 @@ export const ReferenceDirectoryWithFilter = ({
...
     return categoryData.reduce((acc: FilteredCategoryData[], category) => {
       const filteredSubcats = category.subcats.reduce(
-        (subAcc, subcat) => {
+        (subAcc :typeof category.subcats, subcat) => {
           const filteredEntries = subcat.entries.filter((entry) =>
             entry.data.title
               .toLowerCase()
               .includes(searchKeyword.toLowerCase()),
           );
+          if (subcat.entry &&
```
Comment (davepagurek) [inline src/components/ReferenceDirectoryWithFilter/index.tsx]: Could we format this like the brackets in [this section](https://github.com/processing/p5.js-website/blob/678a03d2092c3e99e571b7713f8007f7908fe37e/src/scripts/parsers/reference.ts#L136-L146), where the parts in the brackets are indented in once? e.g.:
```js
if (
  condition1 &&
  condition2
) {
  doSomething(); // code here, indented in once too
}
```
Currently, I the spacing in the if condition is a tad inconsistent, and the body of the if statement is indented with just one space instead of two.

File: src/components/ReferenceDirectoryWithFilter/index.tsx [hunk 2]
```diff
@@ -72,18 +72,26 @@ export const ReferenceDirectoryWithFilter = ({
 
     return categoryData.reduce((acc: FilteredCategoryData[], category) => {
       const filteredSubcats = category.subcats.reduce(
-        (subAcc, subcat) => {
+        (subAcc :typeof category.subcats, subcat) => {
```
Comment (davepagurek) [inline src/components/ReferenceDirectoryWithFilter/index.tsx]: Generally in the codebase we put the space after the colon when adding a type (e.g. [in this function.](https://github.com/processing/p5.js-website/blob/678a03d2092c3e99e571b7713f8007f7908fe37e/src/layouts/ReferenceLayout.astro#L28)) Could we change it here to match?
```suggestion
        (subAcc: typeof category.subcats, subcat) => {
```

**Review by davepagurek — COMMENTED** [review]
Thanks @webermayank! The functionality looks great! I just left some minor comments to try to make the formatting consistent with the rest of the codebase.

**Comment by webermayank** [comment]
@davepagurek , is it okay now ? 
I'll remember to always follow the code formatting carefully for future

**Review by davepagurek — APPROVED** [review]
Thanks, looks great!

**Comment by davepagurek** [comment]
Also no worries about code formatting, it's not super important, just a nice thing to have if everything else works 🙂
