### PR TITLE
Fix for #1143 Added p5.min.js in such a way that it prevents a race condition on th…

### LINKED ISSUE #1143: Multiple Canvases Example Broken
### Most appropriate sections of the p5.js website?

Examples

### What is your operating system?

Windows

### Web browser and version

https://p5js.org/examples/advanced-canvas-rendering-multiple-canvases/

### Actual Behavior

Uncaught ReferenceError: p5 is not defined

### Expected Behavior

I would expect p5 to be defined and the example to be functional

### Steps to reproduce

Visit: https://p5js.org/examples/advanced-canvas-rendering-multiple-canvases/

### Would you like to work on the issue?

Sure

### PR DESCRIPTION
**Pull request by bryanhoffman**
…e example /advanced-canvas-rendering-multiple-canvases

Signed-off-by: Bryan Hoffman

Fixes #1143

### CODE REVIEW

File: src/components/CodeEmbed/index.jsx [hunk 1]
```diff
@@ -2,7 +2,7 @@ import { useState, useEffect, useRef } from "preact/hooks";
 import { useLiveRegion } from '../hooks/useLiveRegion';
 import CodeMirror, { EditorView } from "@uiw/react-codemirror";
 import { javascript } from "@codemirror/lang-javascript";
-import { minifiedLibraryDownloadUrl, cdnLibraryUrl, cdnSoundUrl } from "@/src/globals/globals";
+import { cdnLibraryUrl, cdnSoundUrl } from "@/src/globals/globals";
```
Comment (ksen0) [inline src/components/CodeEmbed/index.jsx:5]: Nice, thank you!
